<html>
<head>
  <head http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
  <head name="Author" content="Claudiu Costin">
  <head name="Keywords" content="linux,irda, infrared, programming">
  <head name="Description" content="Linux-IrDA Project aim is to provide the best open source implementation for IrDA stack, specially made for infrared communications between portable devices">
  <link rev="made" href="mailto:claudiuc@kde.org" title="Linux-Irda Project website">
  <link rel="stylesheet" type="text/css" href="$(ROOT)linuxirda.css">
  <title><get-var title /></title>
  <dump HEAD>
</head>
<body bgcolor="white" text="black" link="blue" alink="red" vlink="magenta" onload="<dump ONLOAD>">
