<br>
<f2>
<navbar:render name="docs2menu" select="intro"><br>
</f2>

<h2>Introduction</h2>

UNDER CONSTRUCTION!

<h2>Documentation</h2>
<f2>
Some consistent documentation you can find at:
<ul>
<li>Linux-Infrared-HOWTO - 
<a href="http://mobilix.org/howtos.html">http://mobilix.org/howtos.html</a>

<li>Linux/IrDA man pages - 
<a href="http://mobilix.org/software.html">http://mobilix.org/software.html</a>

<li>A survery of devices working with Linux-IrDA - 
<a href="http://mobilix.org/ir_misc.html">http://mobilix.org/ir_misc.html</a>
</ul>

</f2>

