<br>
<small>
<navbar:render name="docs2menu" select="intro"><br>
</small>

<h2>Introduction</h2>

UNDER CONSTRUCTION!

<h2>Documentation</h2>

<p>
Some consistent documentation you can find at:
<ul>
<li>Linux-Infrared-HOWTO - 
<a href="http://tuxmobil.org/howtos.html">http://tuxmobil.org/howtos.html</a>

<li>Linux/IrDA man pages - 
<a href="http://tuxmobil.org/software.html">http://tuxmobil.org/software.html</a>

<li>A survery of devices working with Linux-IrDA - 
<a href="http://tuxmobil.org/ir_misc.html">http://tuxmobil.org/ir_misc.html</a>
</ul>


