New version of irda-utils&nbsp;:
<UL>
<LI><li><a href="http://irda.sourceforge.net/ftp/irda-utils/irda-utils-0.9.15.tar.gz">irda-utils-0.9.15</A>&nbsp;:
add new dongles drivers, new irdadump formating options, fix irdadump
TTP and IrCOMM decoding, add LAP QoS decoding, fix irattach error
detection, and add new socket samples. With this version, you can't
use the incorrect form <B>irattach irda0 -s 1</B> any longer, you must
use <B>irattach irda0 -s</B> instead.

<LI><li><a href="http://irda.sourceforge.net/ftp/irda-utils/irda-utils-0.9.16-pre6.tar.gz">irda-utils-0.9.16-pre6</A>&nbsp;:
fixes a few irdadump bugs and allow to disable irdadump parsing, adds
irnetd, and improve man pages.
</UL>

