
<h2>About Linux-IrDA Project</h2>

<f2>
Welcome to the Linux-IrDA project. The overall goal of this project is to make an
implementation of the IrDA<sup><font size="-1">TM</font></sup> standards specifications for
the Linux kernel. The code is licensed under the GNU Public licence (GPL) and is now
included in Linux-2.2.x and Linux 2.4.x kernel series.<br>
<br>
Why IrDA? IrDA is simply much more fun than other technologies! Put your hand in the beam
and watch your adaptive applications do their best.<br>
<br>
IrDA<sup><font size="-1">TM</font></sup> (Infrared Data Association) is an industry standard
for infrared wireless communication. Most laptops sold today are equipped with an IrDA compliant
infrared transceiver, which enables you to communicate with devices such as printers, modems,
fax, LAN, and other laptops. Speeds range from 2400bps-4Mbps.<br>
<br>
<a href="http://sourceforge.net">Sourceforge</a> kindly offer web space, bandwith, mailing lists
and CVS resources to operate Linux-IrDA Project. We want to thank them for such nice support
for open-source projects.
</f2>

<h2>Project History</h2>

<f2>
The project started at the end of 1997 with the name Linux/IrDA. Due to some troubles with the
name IrDA, which is trademarked by the Infrared Data Association IrDA, the name was changed to
Linux/IR. At the end of 1998 the the relationship between both became better and the name was
changed to Linux/IrDA again. Since February 1999 the project is an official member of IrDA.<br>
<br>
Please notice that although we are a member of IrDA, the Linux-IrDA protocol stack is not
certified by IrDA! (but this is definitively one of our future goals). Go
<a href="http://www.irda.org/prodlist/linux.asp">here</a> to see what IrDA
themselves has written about us.<br>
</f2>