
<h2>Chipsets</h2>

<f2>
Here is list of IrDA chipsets and their functional status relative to
Linux kernel. All the stuff marked with (<yes>)
are supported by Linux-IrDA. These with (<gear>) sign are still in development.
Please send more links or info about new manufactured chipsets to have acurate
listing.<br>
<br>
</f2>

<table border="0" cellpadding="0" cellspacing="0" bgcolor="#000000" width="70%" align="center"><tr><td>
<table border="0" cellpadding="3" cellspacing="1" width="100%">
  <tr bgcolor="#ffffe7">
    <td><f2><b>Chipset</b></f2></td>
    <td><f2><b>Status</b></f2></td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td><f2><a href="http://www.cirrus.com/products/overviews/cs8130.html">Crystal CS8130</a></f2></td>
    <td><f2>&nbsp;</f2></td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td><f2><a href="http://www.chips.ibm.com/products/infrared/products/ircntrl.html">IBM31T1502, IBM31T1602</a></f2></td>
    <td><f2><yes></f2></td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td><f2><a href="http://www.nsc.com/pf/PC/PC87108.html">NSC PC87108</a></f2></td>
    <td><f2><yes></f2></td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td><f2><a href="http://www.nsc.com/pf/PC/PC87338.html">NSC PC87338</a></f2></td>
    <td><f2>&nbsp;</f2></td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td><f2><a href="http://www.national.com/pf/PC/PC97338.html">NSC PC97338</a></f2></td>
    <td><f2><yes></f2></td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td><f2>Sharp UIRCC</f2></td>
    <td><f2><gear></f2></td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td><f2><a href="http://www.smsc.com/main/datasheet.html">SMC IrCC chipset</a></f2></td>
    <td><f2><gear></f2></td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td><f2><a href="http://www.ti.com/sc/docs/folders/analog/tir2000.html">TIR-2000</a></f2></td>
    <td><f2><gear></f2></td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td><f2>Toshiba-Hoboe</f2></td>
    <td><f2><yes></f2></td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td><f2>VLSI-VL82C147</f2></td>
    <td><f2><gear></f2></td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td><f2><a href="http://www.winbond.com/produ/w83977faf.htm">Winbond W83977AF</a></f2></td>
    <td><f2><yes></f2></td>
  </tr>
</table>
</td></tr></table>

