
<h2>Companies</h2>

<p>
Below is the list with companies wich offer or develop IrDA devices,
chipsets and many more:<br>
<br>
&nbsp; <a href="http://www.actisys.com">ACTiSYS</a><br>
&nbsp; <a href="http://www.belkin.com">Belkin</a><br>
&nbsp; <a href="http://www.calibre-inc.com">Calibre</a><br>
&nbsp; <a href="http://www.casio.co.jp">Casio</a><br>
&nbsp; <a href="http://www.cirrus.com">Cirrus Logic</a><br>
&nbsp; <a href="http://www.clarinetsys.com/">Clarinet Systems</a><br>
&nbsp; <a href="http://www.countersys.com">Counterpoint</a><br>
&nbsp; <a href="http://www.embednet.com">EMBEDnet</a><br>
&nbsp; <a href="http://www.ericsson.com">Ericsson</a><br>
&nbsp; <a href="http://www.extendsys.com">Extended Systems</a>
&nbsp; <a href="http://www.extendsys.com/products/infrared/">(ir)</a><br>
&nbsp; <a href="http://www.grenwichinst.com">Greenwich</a><br>
&nbsp; <a href="http://www.hcc.ca">HCC</a><br>
&nbsp; <a href="http://www.hp.com">HP</a>
&nbsp; <a href="http://www.hp.com/HP-COMP/ir/center/">(ir)</a><br>
&nbsp; <a href="http://www.ibm.com">IBM</a>
&nbsp; <a href="http://www.chips.ibm.com/products/infrared/">(ir)</a><br>
&nbsp; <a href="http://www.integration.com">Integration</a><br>
&nbsp; <a href="http://www.irda.org">IrDA</a><br>
&nbsp; <a href="http://www.irdatacorp.com/">iRDATA Corp</a><br>
&nbsp; <a href="http://www.kcticom/">KC Technology</a><br>
&nbsp; <a href="http://www.microsoft.com">Microsoft</a>
&nbsp; <a href="http://www.microsoft.com/hwdev/infrared/">(ir)</a><br>
&nbsp; <a href="http://www.mot.com">Motorola</a><br>
&nbsp; <a href="http://www.nsc.com">National Semiconductor</a><br>
&nbsp; <a href="http://www.nokia.com">Nokia</a><br>
&nbsp; <a href="http://www.novalog.com">Novalog</a><br>
&nbsp; <a href="http://www.ntt.co.jp">NTT</a><br>
&nbsp; <a href="http://www.osw.co.jp">Okaya</a>
&nbsp; <a href="http://www.osw.co.jp/products/irda/index.htm">(ir)</a><br>
&nbsp; <a href="http://www.palm.com">Palm</a><br>
&nbsp; <a href="http://www.parallax-research.com/">Parallax</a><br>
&nbsp; <a href="http://www.psion.com">Psion</a><br>
&nbsp; <a href="http://www.pumatech.com">Puma</a><br>
&nbsp; <a href="http://www.selectechltd.com/">SelecTech</a><br>
&nbsp; <a href="http://www.sharpsec.com">Sharp</a><br>
&nbsp; <a href="http://www.spectrixcorp.com">Spextrix</a><br>
&nbsp; <a href="http://www.tekram.com">Tekram</a>
&nbsp; <a href="http://www.tekram.com/infrared.asp">(ir)</a><br>
&nbsp; <a href="http://www.ti.com">Texas-Instruments</a>
&nbsp; <a href="http://www.ti.com/sc/docs/msp/irda/selguide.htm">(ir)</a><br>
&nbsp; <a href="http://www.toshiba.com">Toshiba</a><br>
&nbsp; <a href="http://www.vishay.de/">Vishay</a><br>
&nbsp; <a href="http://www.winbond.com/">Winbond</a><br>

