
<h2>Contact Information</h2>

<f2>
<font color="#ff0000"><b>NOTE:</b> The old mailling list <i>linux-irda@pasta.cs.uit.no</i> is no longer available!</font><br>
<br>
You are welcome to use the Linux-IrDA mailing list for posting questions, answers,
bug-reports, patches, suggestions and comments about Linux-IrDA.
Please note that mailinglist doesn't accept mail from non-subscribers. This is to
provide high signal-noise ratio and avoid spam. Thanks for understanding.<br>
The mailing list posting address is:<br>
&nbsp; &nbsp;<b><a href="mailto:irda-users@lists.sourceforge.net">irda-users@lists.sourceforge.net</a></b>.<br>
<ul>
  <li><f2>
    <b>list archive:</b> you can also browse the list-archive to view previous postings at
    <a href="http://www.geocrawler.com/redir-sf.php3?list=irda-users">Geocrawler</a>
  </f2></li>
  <li><f2>
    <b>for subscribing:</b> point your browser to
      <a href="http://lists.sourceforge.net/lists/listinfo/irda-users">http://lists.sourceforge.net/lists/listinfo/irda-users</a>
    and here you will find Linux-IrDA mailinglist control page. Read on "Subscribig to
    Linux-IrDA" section and fill email address field and password field (twice). Then press
    "Subscribe" button.
  </f2></li>
  <li><f2>
    <b>for unsubscribing:</b> point your browser to
      <a href="http://lists.sourceforge.net/lists/listinfo/irda-users">http://lists.sourceforge.net/mailman/listinfo/irda-users</a>
    and here you will find Linux-IrDA mailinglist control page. Read on "Linux-IrDA
    subscribers" section and fill email address in bottom field. Then press "Edit Options" button.
    Now you are in your personal page. On "Unsubscribing from Linux-IrDA" section enter the
    password when you subscribed and press "Unsubcribe" button.
  </f2></li>
</ul>
</f2>

<h2>Developers</h2>

<f2>
This list is not intended to promote some people names, just to enter in
quick contact with principal maintainers for various aspects of Linux-IrDA
Project.<br>
<br>

<h3>Development</h3>
<b>Jean Tourrilhes</b> - core team member<br>
website: <a href="http://www.hpl.hp.com/personal/Jean_Tourrilhes/IrDA/IrDA.html">http://www.hpl.hp.com/personal/Jean_Tourrilhes/IrDA/IrDA.html</a><br>
status: actively involved, IrNet implementor and many improvements
on stack.<br>
<b>Dag Brattli</b> - core team member and master of Linux-IrDA stack<br>
website: <a href="http://www.brattli.net/dag/">http://www.brattli.net/dag/</a><br>
status: currently he have little time to spend on Linux IrDA<br>
<br>

<h3>Documentation</h3>
<b>Werner Heuser</b> - author and maintainer of Linux-Infrared HOWTO<br>
email: <a href="mailto:wehe@mobilix.org">wehe@mobilix.org</a><br>
status: maintain IrDA HOWTO and also his <a href="http://www.mobilix.org">Mobilix</a>
website and <a href="http://mobilix.org/howtos.html">Linux-Laptop Guide</a><br>

<h3>Website</h3>
<b>Claudiu Costin</b> - maintainer of Linux-IrDA web site<br>
email: <a href="mailto:claudiuc@kde.org">claudiuc@kde.org</a><br>
status: currently he maintain this web site and look for feedback about it
<br>


</f2>