
<h2>Credits</h2>

<f2>
We want to thank you to all people which contributed on Linux-IrDA
Project. If you know you contributed somehow and your name is not listed
just send a mail to <webmaster>.
</f2>

<h3>Main developers</h3>
<f2>
&nbsp;&nbsp;Dag Brattli<br>
&nbsp;&nbsp;Jean Tourrilhes<br>
&nbsp;&nbsp;Thomas Davis - retired <br>
&nbsp;&nbsp;Takahide Higuchi - retired<br>


</f2>

<h3>Source code contributors</h3>
<f2>
&nbsp;&nbsp;Shimizu Takuya<br>
&nbsp;&nbsp;Benjamin Kong<br>
&nbsp;&nbsp;Ryan Shillington<br>
&nbsp;&nbsp;Izar Tarandach<br>
</f2>

<h3>Documentation</h3>
<f2>
Werner Heuser<br>
</f2>

<h3>Testing, suggestions, flames</h3>
<f2>
&nbsp;&nbsp;Ralf Zabka<br>
&nbsp;&nbsp;Benny Amorsen<br>
&nbsp;&nbsp;Lichen Wang<br>
&nbsp;&nbsp;Ryan Shillington<br>
&nbsp;&nbsp;Richard Titmuss<br>
&nbsp;&nbsp;Fons Botman<br>
&nbsp;&nbsp;Rui Oliveira<br>
&nbsp;&nbsp;Jon Howell<br>
&nbsp;&nbsp;Carlos Vidal<br>
&nbsp;&nbsp;Joonas Lehtinen<br>
&nbsp;&nbsp;Markus Schill<br>
&nbsp;&nbsp;Bjoern Hansson<br>
&nbsp;&nbsp;Pawel Machek<br>
&nbsp;&nbsp;Ho Chin Keong<br>
&nbsp;&nbsp;Bjoern Mork<br>
&nbsp;&nbsp;Andreas Butz<br>
&nbsp;&nbsp;Tang Ning<br>
&nbsp;&nbsp;Philip Blundell<br>
&nbsp;&nbsp;Toni van de Wiel<br>
&nbsp;&nbsp;Stefan Dahlke<br>
&nbsp;&nbsp;Ales Dryak<br>
&nbsp;&nbsp;Richard Donkin<br>
&nbsp;&nbsp;Wessel de Roode<br>
&nbsp;&nbsp;Andrew Chadwick<br>
&nbsp;&nbsp;James McKenzie<br>
&nbsp;&nbsp;Gerd Knorr<br>
&nbsp;&nbsp;Claudiu Costin<br>
&nbsp;&nbsp;K-H. Eischer<br>
&nbsp;&nbsp;Alessio Massaro<br>
&nbsp;&nbsp;Igor Pesando<br>
&nbsp;&nbsp;Ove Ewerlid<br>
&nbsp;&nbsp;Gerhard Gonter<br>
&nbsp;&nbsp;Florian Lohoff<br>
&nbsp;&nbsp;Mathieu Arnold<br>
&nbsp;&nbsp;Harald Milz<br>
&nbsp;&nbsp;Mike Groeneweg<br>
&nbsp;&nbsp;Christian Rishoej<br>
&nbsp;&nbsp;Guenther Wieser<br>
&nbsp;&nbsp;Timo Felbinger<br>
&nbsp;&nbsp;Arthur Tyde<br>
&nbsp;&nbsp;Bryan Abshier<br>
&nbsp;&nbsp;Tollef Fog Heen<br>
</f2>

