
<h2>Devices</h2>

<f2>
Here is list of IrDA devices and their functional status relative to
Linux kernel. All the stuff marked with (<yes>)
are supported by Linux-IrDA. These with (<gear>) sign are still in development.
Please send more links or info about new manufactured chipsets to have acurate
listing.<br>
<br>
<b>Notice:</b> Werner Heuser have more up to date page at
<a href="http://mobilix.org/ir_misc.html">http://mobilix.org/ir_misc.html</a>
with devices working with Linux-IrDA.
Soon, this section will be in sync with his page.<br>
</f2>

<h3>Mobile Phones</h3>
<div align="left">
<table border="0" cellpadding="0" cellspacing="0" bgcolor="#000000" width="70%"><tr><td>
<table border="0" cellpadding="3" cellspacing="1" width="100%">
  <tr bgcolor="#ffffe7">
    <td><f2><b>Devices</b></f2></td>
    <td><f2><b>Status</b></f2></td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td><f2>Ericsson I 888 World</f2></td>
    <td><f2>&nbsp;</f2></td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td><f2>Ericsson SH888</f2></td>
    <td><f2>&nbsp;</f2></td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td><f2>Ericsson GH688/GH768 + DI27</f2></td>
    <td><f2>&nbsp;</f2></td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td><f2>Motorola L7089</f2></td>
    <td><f2>&nbsp;</f2></td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td><f2>Nokia 8810</f2></td>
    <td><f2>&nbsp;</f2></td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td><f2>Nokia 9110</f2></td>
    <td><f2>&nbsp;</f2></td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td><f2>Nokia NM-207</f2></td>
    <td><f2>&nbsp;</f2></td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td><f2>Siemens S25</f2></td>
    <td><f2>&nbsp;</f2></td>
  </tr>
</table>
</td></tr></table>
</div>


<h3>Laptops</h3>
<div align="left">
<table border="0" cellpadding="0" cellspacing="0" bgcolor="#000000" width="70%"><tr><td>
<table border="0" cellpadding="3" cellspacing="1" width="100%">
  <tr bgcolor="#ffffe7">
    <td><f2><b>Devices</b></f2></td>
    <td><f2><b>Status</b></f2></td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td><f2>Asus L7300</f2></td>
    <td><f2>&nbsp;</f2></td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td><f2>Acer Acernote 350</f2></td>
    <td><f2>&nbsp;</f2></td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td><f2>Digital HiNote VP565</f2></td>
    <td><f2>&nbsp;</f2></td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td><f2>Fujitsu Lifebook B110</f2></td>
    <td><f2>&nbsp;</f2></td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td><f2>HP Omnibook 800CT</f2></td>
    <td><f2>&nbsp;</f2></td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td><f2>HP Omnibook 5500</f2></td>
    <td><f2>&nbsp;</f2></td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td><f2>HP Omnibook 5700</f2></td>
    <td><f2>&nbsp;</f2></td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td><f2>Palmax PD-1x00 series</f2></td>
    <td><f2>&nbsp;</f2></td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td><f2>IBM Thinkpad 390E</f2></td>
    <td><f2>&nbsp;</f2></td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td><f2>IBM Thinkpad 560X</f2></td>
    <td><f2>&nbsp;</f2></td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td><f2>IBM Thinkpad 560Z</f2></td>
    <td><f2>&nbsp;</f2></td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td><f2>IBM Thinkpad 570</f2></td>
    <td><f2>&nbsp;</f2></td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td><f2>IBM Thinkpad 600E</f2></td>
    <td><f2>&nbsp;</f2></td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td><f2>IBM Thinkpad 600X</f2></td>
    <td><f2>&nbsp;</f2></td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td><f2>IBM Thinkpad 770</f2></td>
    <td><f2>&nbsp;</f2></td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td><f2>Sharp Mebius PC-PJ2-M2</f2></td>
    <td><f2>&nbsp;</f2></td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td><f2>Sony Vaio Z505SX</f2></td>
    <td><f2>&nbsp;</f2></td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td><f2>Sony Vaio PCG737</f2></td>
    <td><f2>&nbsp;</f2></td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td><f2>Toshiba Portege 300CT</f2></td>
    <td><f2>&nbsp;</f2></td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td><f2>Toshiba Portege 320CT</f2></td>
    <td><f2>&nbsp;</f2></td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td><f2>Toshiba Portege 3010CT</f2></td>
    <td><f2>&nbsp;</f2></td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td><f2>Toshiba Portege 3015CT</f2></td>
    <td><f2>&nbsp;</f2></td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td><f2>Toshiba Portege 3020CT</f2></td>
    <td><f2>&nbsp;</f2></td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td><f2>Toshiba Libretto 50CT</f2></td>
    <td><f2>&nbsp;</f2></td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td><f2>Toshiba Libretto 70CT</f2></td>
    <td><f2>&nbsp;</f2></td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td><f2>Toshiba Libretto 100CT</f2></td>
    <td><f2>&nbsp;</f2></td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td><f2>Toshiba Libretto 1000CT</f2></td>
    <td><f2>&nbsp;</f2></td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td><f2>Toshiba Satellite 230CX</f2></td>
    <td><f2>&nbsp;</f2></td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td><f2>Toshiba SatellitePro 440</f2></td>
    <td><f2>&nbsp;</f2></td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td><f2>Toshiba SatellitePro 440CDX</f2></td>
    <td><f2>&nbsp;</f2></td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td><f2>Toshiba SatellitePro 480</f2></td>
    <td><f2>&nbsp;</f2></td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td><f2>Toshiba SatellitePro 490XCDT</f2></td>
    <td><f2>&nbsp;</f2></td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td><f2>Toshiba Satellite 2520</f2></td>
    <td><f2>&nbsp;</f2></td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td><f2>Toshiba Satellite 4000CDS</f2></td>
    <td><f2>&nbsp;</f2></td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td><f2>Toshiba Satellite 4025CDT</f2></td>
    <td><f2>&nbsp;</f2></td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td><f2>Toshiba Tecra 500CDT</f2></td>
    <td><f2>&nbsp;</f2></td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td><f2>Toshiba Tecra 730CDT</f2></td>
    <td><f2>&nbsp;</f2></td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td><f2>Toshiba Tecra 730XCDT</f2></td>
    <td><f2>&nbsp;</f2></td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td><f2>Toshiba Tecra 740CDT</f2></td>
    <td><f2>&nbsp;</f2></td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td><f2>Toshiba Tecra 750DVD</f2></td>
    <td><f2>&nbsp;</f2></td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td><f2>Toshiba Tecra 750CDT</f2></td>
    <td><f2>&nbsp;</f2></td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td><f2>Toshiba Tecra 780</f2></td>
    <td><f2>&nbsp;</f2></td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td><f2>Toshiba Tecra 8000</f2></td>
    <td><f2>&nbsp;</f2></td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td><f2>Twinhead Slimnote XL</f2></td>
    <td><f2>&nbsp;</f2></td>
  </tr>
</table>
</td></tr></table>
</div>


<h3>Personal Computers</h3>
<div align="left">
<table border="0" cellpadding="0" cellspacing="0" bgcolor="#000000" width="70%"><tr><td>
<table border="0" cellpadding="3" cellspacing="1" width="100%">
  <tr bgcolor="#ffffe7">
    <td><f2><b>Devices</b></f2></td>
    <td><f2><b>Status</b></f2></td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td><f2>NetWinder</f2></td>
    <td><f2>&nbsp;</f2></td>
  </tr>
</table>
</td></tr></table>
<br>

<h3>Palmtops and PDAs</h3>
<div align="left">
<table border="0" cellpadding="0" cellspacing="0" bgcolor="#000000" width="70%"><tr><td>
<table border="0" cellpadding="3" cellspacing="1" width="100%">
  <tr bgcolor="#ffffe7">
    <td><f2><b>Devices</b></f2></td>
    <td><f2><b>Status</b></f2></td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td><f2>HP Jornada 680 </f2></td>
    <td><f2>&nbsp;</f2></td>
  </tr>
</table>
</td></tr></table>
</div>

<h3>Printers</h3>
<div align="left">
<table border="0" cellpadding="0" cellspacing="0" bgcolor="#000000" width="70%"><tr><td>
<table border="0" cellpadding="3" cellspacing="1" width="100%">
  <tr bgcolor="#ffffe7">
    <td><f2><b>Devices</b></f2></td>
    <td><f2><b>Status</b></f2></td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td><f2>Canon BJC 80</f2></td>
    <td><f2>&nbsp;</f2></td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td><f2>HP LaserJet 6MP</f2></td>
    <td><f2>&nbsp;</f2></td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td><f2>HP LaserJet 2100TN</f2></td>
    <td><f2>&nbsp;</f2></td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td><f2>HP LaserJet 4100DN</f2></td>
    <td><f2>&nbsp;</f2></td>
  </tr>
</table>
</td></tr></table>
</div>


<h3>Scanners</h3>
<div align="left">
<table border="0" cellpadding="0" cellspacing="0" bgcolor="#000000" width="70%"><tr><td>
<table border="0" cellpadding="3" cellspacing="1" width="100%">
  <tr bgcolor="#ffffe7">
    <td><f2><b>Devices</b></f2></td>
    <td><f2><b>Status</b></f2></td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td><f2>HP CapShare 920</f2></td>
    <td><f2>&nbsp;</f2></td>
  </tr>
</table>
</td></tr></table>
</div>