
<h2>Devices</h2>

<p>
Here is list of IrDA devices and their functional status relative to
Linux kernel. All the stuff marked with (<yes>)
are supported by Linux-IrDA. These with (<gear>) sign are still in development.
Please send more links or info about new manufactured chipsets to have acurate
listing.

<p>
<b>Notice:</b> Werner Heuser have more up to date page at
<a href="http://tuxmobil.org/ir_misc.html">http://tuxmobil.org/ir_misc.html</a>
with devices working with Linux-IrDA.
This section may not be in sync with his page.

<h3>Mobile Phones</h3>
<div align="left">
<table border="0" cellpadding="0" cellspacing="0" bgcolor="#000000" width="70%"><tr><td>
<table border="0" cellpadding="3" cellspacing="1" width="100%">
  <tr bgcolor="#ffffe7">
    <td><b>Devices</b></td>
    <td><b>Status</b></td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td>Ericsson I 888 World</td>
    <td>&nbsp;</td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td>Ericsson SH888</td>
    <td>&nbsp;</td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td>Ericsson GH688/GH768 + DI27</td>
    <td>&nbsp;</td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td>Motorola L7089</td>
    <td>&nbsp;</td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td>Nokia 8810</td>
    <td>&nbsp;</td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td>Nokia 9110</td>
    <td>&nbsp;</td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td>Nokia NM-207</td>
    <td>&nbsp;</td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td>Siemens S25</td>
    <td>&nbsp;</td>
  </tr>
</table>
</td></tr></table>
</div>


<h3>Laptops</h3>
<div align="left">
<table border="0" cellpadding="0" cellspacing="0" bgcolor="#000000" width="70%"><tr><td>
<table border="0" cellpadding="3" cellspacing="1" width="100%">
  <tr bgcolor="#ffffe7">
    <td><b>Devices</b></td>
    <td><b>Status</b></td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td>Asus L7300</td>
    <td>&nbsp;</td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td>Acer Acernote 350</td>
    <td>&nbsp;</td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td>Digital HiNote VP565</td>
    <td>&nbsp;</td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td>Fujitsu Lifebook B110</td>
    <td>&nbsp;</td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td>HP Omnibook 800CT</td>
    <td>&nbsp;</td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td>HP Omnibook 5500</td>
    <td>&nbsp;</td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td>HP Omnibook 5700</td>
    <td>&nbsp;</td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td>Palmax PD-1x00 series</td>
    <td>&nbsp;</td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td>IBM Thinkpad 390E</td>
    <td>&nbsp;</td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td>IBM Thinkpad 560X</td>
    <td>&nbsp;</td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td>IBM Thinkpad 560Z</td>
    <td>&nbsp;</td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td>IBM Thinkpad 570</td>
    <td>&nbsp;</td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td>IBM Thinkpad 600E</td>
    <td>&nbsp;</td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td>IBM Thinkpad 600X</td>
    <td>&nbsp;</td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td>IBM Thinkpad 770</td>
    <td>&nbsp;</td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td>Sharp Mebius PC-PJ2-M2</td>
    <td>&nbsp;</td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td>Sony Vaio Z505SX</td>
    <td>&nbsp;</td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td>Sony Vaio PCG737</td>
    <td>&nbsp;</td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td>Toshiba Portege 300CT</td>
    <td>&nbsp;</td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td>Toshiba Portege 320CT</td>
    <td>&nbsp;</td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td>Toshiba Portege 3010CT</td>
    <td>&nbsp;</td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td>Toshiba Portege 3015CT</td>
    <td>&nbsp;</td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td>Toshiba Portege 3020CT</td>
    <td>&nbsp;</td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td>Toshiba Libretto 50CT</td>
    <td>&nbsp;</td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td>Toshiba Libretto 70CT</td>
    <td>&nbsp;</td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td>Toshiba Libretto 100CT</td>
    <td>&nbsp;</td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td>Toshiba Libretto 1000CT</td>
    <td>&nbsp;</td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td>Toshiba Satellite 230CX</td>
    <td>&nbsp;</td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td>Toshiba SatellitePro 440</td>
    <td>&nbsp;</td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td>Toshiba SatellitePro 440CDX</td>
    <td>&nbsp;</td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td>Toshiba SatellitePro 480</td>
    <td>&nbsp;</td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td>Toshiba SatellitePro 490XCDT</td>
    <td>&nbsp;</td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td>Toshiba Satellite 2520</td>
    <td>&nbsp;</td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td>Toshiba Satellite 4000CDS</td>
    <td>&nbsp;</td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td>Toshiba Satellite 4025CDT</td>
    <td>&nbsp;</td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td>Toshiba Tecra 500CDT</td>
    <td>&nbsp;</td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td>Toshiba Tecra 730CDT</td>
    <td>&nbsp;</td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td>Toshiba Tecra 730XCDT</td>
    <td>&nbsp;</td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td>Toshiba Tecra 740CDT</td>
    <td>&nbsp;</td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td>Toshiba Tecra 750DVD</td>
    <td>&nbsp;</td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td>Toshiba Tecra 750CDT</td>
    <td>&nbsp;</td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td>Toshiba Tecra 780</td>
    <td>&nbsp;</td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td>Toshiba Tecra 8000</td>
    <td>&nbsp;</td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td>Twinhead Slimnote XL</td>
    <td>&nbsp;</td>
  </tr>
</table>
</td></tr></table>
</div>


<h3>Personal Computers</h3>
<div align="left">
<table border="0" cellpadding="0" cellspacing="0" bgcolor="#000000" width="70%"><tr><td>
<table border="0" cellpadding="3" cellspacing="1" width="100%">
  <tr bgcolor="#ffffe7">
    <td><b>Devices</b></td>
    <td><b>Status</b></td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td>NetWinder</td>
    <td>&nbsp;</td>
  </tr>
</table>
</td></tr></table>
<br>

<h3>Palmtops and PDAs</h3>
<div align="left">
<table border="0" cellpadding="0" cellspacing="0" bgcolor="#000000" width="70%"><tr><td>
<table border="0" cellpadding="3" cellspacing="1" width="100%">
  <tr bgcolor="#ffffe7">
    <td><b>Devices</b></td>
    <td><b>Status</b></td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td>HP Jornada 680 </td>
    <td>&nbsp;</td>
  </tr>
</table>
</td></tr></table>
</div>

<h3>Printers</h3>
<div align="left">
<table border="0" cellpadding="0" cellspacing="0" bgcolor="#000000" width="70%"><tr><td>
<table border="0" cellpadding="3" cellspacing="1" width="100%">
  <tr bgcolor="#ffffe7">
    <td><b>Devices</b></td>
    <td><b>Status</b></td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td>Canon BJC 80</td>
    <td>&nbsp;</td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td>HP LaserJet 6MP</td>
    <td>&nbsp;</td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td>HP LaserJet 2100TN</td>
    <td>&nbsp;</td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td>HP LaserJet 4100DN</td>
    <td>&nbsp;</td>
  </tr>
</table>
</td></tr></table>
</div>


<h3>Scanners</h3>
<div align="left">
<table border="0" cellpadding="0" cellspacing="0" bgcolor="#000000" width="70%"><tr><td>
<table border="0" cellpadding="3" cellspacing="1" width="100%">
  <tr bgcolor="#ffffe7">
    <td><b>Devices</b></td>
    <td><b>Status</b></td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td>HP CapShare 920</td>
    <td>&nbsp;</td>
  </tr>
</table>
</td></tr></table>
</div>