
<h2>Dongles</h2>

<p>
Here is list of IrDA dongles and their functional status relative to
Linux kernel. All the stuff marked with (<yes>)
are supported by Linux-IrDA. These with (<gear>) sign are still in development.
Please send more links or info about new manufactured dongles to have acurate
listing.




<table border="0" cellpadding="0" cellspacing="0" bgcolor="#000000" width="70%" align="center"><tr><td>
<table border="0" cellpadding="3" cellspacing="1" width="100%">
  <tr bgcolor="#ffffe7">
    <td><b>Dongle</b></td>
    <td><b>Status</b></td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td><a href="http://www.actisys.com/ACT200-220.html">ACTiSYS ACT-IR200L, IR220L, IR220L+, IR220LN</a></td>
    <td><yes></td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td>Adaptec Airport 1000, 2000</td>
    <td><yes></td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td><a href="http://www.extendsys.com/products/infrared/jeteyepc.html">Extendsys JetEye PC (ESI-9680)</a></td>
    <td><yes></td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td><a href="http://www.greenwichinst.com/pdahpc.html">Greenwich GIrBIL</a></td>
    <td><yes></td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td><a href="http://www.bgmicro.com/lmad.htm">Infrared Adapter</a></td>
    <td>&nbsp;</td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td><a href="http://www.novalog.com/products.html">Novalog BayBeamer</a></td>
    <td>&nbsp;</td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td><a href="http://www.parallax-research.com/litelink.html">Parallax Litelink</a></td>
    <td><yes></td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td><a href="http://www.selectechltd.com/ADM.HTM">SelecTech AirData Mouse</a></td>
    <td>&nbsp;</td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td><a href="http://www.tekram.com/Hot_Products.asp?Product=IR-210">Tekram IRmate IR-210B</a></td>
    <td><yes></td>
  </tr>
  <tr bgcolor="#ffffe7">
    <td><a href="http://www.pumatech.com/serial_infrared.html">Puma Serial Infrared Adapters</a></td>
    <td>&nbsp;</td>
  </tr>
</table>
</td></tr></table>

