
<h2>Download</h2>

<f2>
Linux-IrDA project members and contributors has released
various files, packages and patches for kernel space IrDA
stack and user spaces utilities. Please announce the <webmaster>
if you contributed something and want to be put on project
<a href="http://irda.sourceforge.net/ftp/">FTP</a> area. That way everyone will have quick access to software
resources.
</f2>

<h3><a href="http://sourceforge.net/project/showfiles.php?group_id=5616">SourceForge Download Area</a></h3>
<f2>
This zone list all released packages for Linux-IrDA Project. Currently it include only
<b>irda-utils</b>. Binaries packages are available as RPM.<br>
&nbsp;&nbsp;<a href="http://sourceforge.net/project/showfiles.php?group_id=5616">http://sourceforge.net/project/showfiles.php?group_id=5616</a>
</f2>


<h3><a href="http://irda.sourceforge.net/ftp/irda-utils/">IrDA Utils</a></h3>
<f2>
Package which consist from user space utilities which control
IrDA stack and a bunch of little programs serving as examples
and tools for IrDA applications. Here are some old releases if you
insist running old kernel versions.<br>
&nbsp;&nbsp;<a href="http://irda.sourceforge.net/ftp/irda-utils/">http://irda.sourceforge.net/ftp/irda-utils/</a>
</f2>

<h3><a href="http://irda.sourceforge.net/ftp/drivers/">Drivers</a></h3>
<f2>
Here are some drivers for various IrDA hardware found mostly on laptops. Note
that some ones may not function 100% properly and may not have proper documentation.
We hope soon this will change and may be you can contribute if you feel.<br>
&nbsp;&nbsp;<a href="http://irda.sourceforge.net/ftp/drivers/">http://irda.sourceforge.net/ftp/drivers/</a>
</f2>

<h3><a href="http://irda.sourceforge.net/ftp/patches/">Kernel Patches</a></h3>
<f2>
Lot of kernel patches from ancient Linux-IrDA to present. You can build your own
bleeding edge custom kernel, play with your toy, find bugs, fix them and make your
own patches available here.<br>
&nbsp;&nbsp;<a href="http://irda.sourceforge.net/ftp/patches/">http://irda.sourceforge.net/ftp/patches/</a>
</f2>

