
<h2>Resources</h2>

<p>
Here is a list of all the IrDA resources I could find. Please
send me more links.
<p>
Next pages from this sections will guide you on Internet places where you can find
companies which support IrDA, chipsets, IrDA dongles and adapters and, of course,
devices which feature IrDA conectivity.
<p>
Werner Heuser, Linux-IrDA HOWTO maintainer have a large collection of informations
about IrDA devices and Linux on laptops documentations. Because there's no laptop
today without IrDA, please take a look before you buy one and want to run IrDA
applications. Sad, but true, some models still lack support for on-board
infrared chipsets or are partialy working. Please visit TuxMobil website at
<a href="http://tuxmobil.org/">http://tuxmobil.org/</a>.

<h2>IrDA Links</h2>
<p>
<ul>

<li>The <a href="http://www.irda.org/">IrDA organization</a>, with on-line specs

<li><a href="http://sourceforge.net/projects/girda/">GIrDA</a>, an
<b>IrDA monitor</b> that display devices in range and support
OpenObex.

<li><a href="http://www.eyetap.org/~tangf/irda_sir_linux.html">Felix
Tang</a> has a page on how to build a <b>cheap SIR dongle</b>.

<li><a href="http://www.csai.unipa.it/peri/toshsat1800-irdasetup/">Daniele
Peri</a> has some utility to help configure <b>Toshiba Satellite 1800</b>
IrDA ports. <a href="$(ROOT)smcinit/">smcinit</a> use it.

<li><a href="http://www.janerob.com/rob/ts5100/irda.html">Rob
Miller</a> has some utility to help configure <b>Toshiba Satellite 5100 
IrDA ports</b>. <a href="$(ROOT)smcinit/">smcinit</a> use it.

<li><a href="http://libxg.free.fr/irda/lib-irda.html">James McKenzie
and Christian Gennerat</a> have done a rewrite of the <b>toshoboe</b>
driver called <b>donauboe</b>

<li><a href="http://www.lysator.liu.se/~torkel/computer/ipaq/irda_cellphone_ppp.html">Tor-Ake Fransson</a> 
have some instructions on how to use Linux with a <b>IrDA
enabled cell phone</b>

<li><a href="http://www.cewindows.net/wce/linux-serial.htm">Arthur Tyde and Bryan Abshier</a> 
have some instructions on how to connect a
<b>WinCE device to Linux</b>

<li><a href="http://gnokii.org/">Gnokii</a>, a package to communicate
with your cellular phone over IrDA and over special made cables.

</ul>



<h2>Related Links</h2>

<p>
<ul>

<li>The <a href="http://sourceforge.net/projects/openobex/">OpenObex
web page</a>, where you will find the latest version of the Obex code.
This protocol allow you to exchange objects (vCard,
vCal) with your Palm or cellular phone over IrDA or BlueTooth.

<li><a href="http://triq.net/obexftp">ObexFTP</a>, an implementation
of <b>FTP over OpenObex</b>, with a nice graphical interface. Also
include a working implementation of <b>OpenObex over Serial</b>
cable. Can be used to browse some cellular phones.

<li><a href="http://www.hpl.hp.com/personal/Jean_Tourrilhes/Linux/Wireless.html">Linux Wireless LAN Howto</a> maintained by Jean Tourrilhes

<li>Also Jean say how to setup <a href="http://www.hpl.hp.com/personal/Jean_Tourrilhes/bt/">BlueTooth on Linux</a>

<li>Linux kernel source <a href="http://www.kernel.org/">archive</a>
(the latest IrDA stack is in the 2.4.X kernels).

</ul>
