#! /bin/sh
#
# network
#
# Initialize or shutdown IrLAN ethernet device drivers
#
# This script should be invoked with two arguments.  The first is the
# action to be taken, either "start", "stop", or "restart".  The
# second is the network interface name.

action=$1
device=$2

case "${action:?}" in
'start')
	/sbin/ifup ${device}
    ;;
'stop')
	/sbin/ifdown ${device}
    ;;
'restart')
    /sbin/ifconfig ${device:?} down up
    ;;
esac
